# This job lets you run
# - all tests: bacon test
# - a specific test: bacon test -- config::test_default_files
# - the tests of a package: bacon test -- -- -p config
[jobs.test]
command = [
  "cargo",
  "nextest",
  "run",
  "--hide-progress-bar",
  "--failure-output",
  "final",
]
need_stdout = true
analyzer = "nextest"
watch = ["db/migrations"]
on_change_strategy = "kill_then_restart"
