[package]
name = "potrin"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "potrin_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.17", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta.22", features = [] }
tauri-plugin-shell = "2.0.0-beta.7"
tauri-plugin-store = "2.0.0-beta.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.120"
anyhow = "1.0.86"
macros = { path = "macros" }
tantivy = "0.22.0"
unicode-normalization = "0.1.20"
cjk = "0.2"
diacritics = "0.2.2"


[dependencies.tauri-plugin-sql]
features = ["sqlite"] # or "postgres", or "mysql"
version = "2.0.0-beta.6"
