[package]
name = "potrin"
version = "0.0.0"
description = "A Tauri App"
authors = ["Joichiro Hayashi"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "potrin_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "=2.0.0-rc.3", features = ["config-toml"] }

[dev-dependencies]
tokio = { version = "^1.39.3", features = ["full"] }

[dependencies]
tauri = { version = "=2.0.0-rc.3", features = ["config-toml"] }
tauri-plugin-store = "2.0.0-rc"
specta = { version = "=2.0.0-rc.20", features = ["uuid", "chrono"] }
specta-typescript = "0.0.7"
tauri-specta = { version = "=2.0.0-rc.17", features = ["derive", "typescript"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
macros = { path = "macros" }
tantivy = "0.22"
unicode-normalization = "0.1.20"
cjk = "0.2"
diacritics = "0.2"
sqlx = { version = "0.8", features = [
  "sqlite",
  "runtime-tokio-native-tls",
  "uuid",
  "chrono",
] }
uuidv7 = "0.1.4"
uuid = "1.10.0"
chrono = { version = "0.4.38", features = ["serde"] }
