productName = "potrin"
version = "0.0.0"
identifier = "com.potrin.dev"

[build]
beforeDevCommand = "pnpm dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "pnpm build"
frontendDist = "../build"

[[app.windows]]
title = "potrin"
width = 800
height = 600

[app.security]
capabilities = [ "main-capability" ]

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
