productName = "potrin"
version = "0.0.0"
identifier = "com.potrin.dev"

[build]
beforeDevCommand = "export DATABASE_URL='sqlite:db/dev.db' && cd src-tauri && cargo make setup-db && cd .. && pnpm dev"
devUrl = "http://localhost:1420"
beforeBuildCommand = "export DATABASE_URL='sqlite:db/dev.db' cd src-tauri && cargo make setup-db && cd .. && pnpm build"
frontendDist = "../build"

[app]
macOSPrivateApi = true

[app.security]
capabilities = ["main-capability"]

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico",
]
