"$schema" = "../gen/schemas/desktop-schema.json"
identifier = "main-capability"
description = "Capability for the main window"
windows = [ "main" ]
permissions = [
  "core:app:default",
  "store:default",
  "store:allow-get",
  "store:allow-set",
  "store:allow-save",
  "store:allow-load"
]

